# Generated by Django 3.1.1 on 2020-10-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_photogallery', '0007_auto_20201011_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturepost',
            name='source',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
