# Generated by Django 3.1.1 on 2020-10-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_photogallery', '0008_auto_20201011_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturepost',
            name='url_height',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='picturepost',
            name='url_width',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
